apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: ns-enable
  project: bharathtest
spec:
  base:
    name: minimal
    version: 2.7.0
  driftWebhook: {}
  namespaceConfig:
    enableSync: true
    syncType: Managed
  type: custom
  version: "2"
