apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: test
  project: bharathtest
spec:
  base:
    name: minimal
    version: 2.4.0
  customAddons:
  - name: nginx
    version: "1"
  driftWebhook:
    enabled: true
  type: custom
  version: "1"
