apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    rafay.dev/description: ""
  name: nginx
  project: bharathtest
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: bharath-mks-wwf
    - key: rafay.dev/clusterName
      value: import
  resourceQuotas: {}
